### ISSUE TITLE
Typescript tasks

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber-js#1269]
Now that we have converted to Typescript have a few post merge tasks that would be nice:

- [x] tsconfig - set noImplicitAny to true (#1286)
- [x] tsconfig - set noImplicitThis to true (#1283)
- [x] tsconfig - set noImplicitReturns to true (#1286)
- [x] checkout using https://api-extractor.com/ - better to wait until after https://github.com/microsoft/rushstack/issues/1029 is fixed
- [x] add changelog entry noting the rewrite to TypeScript (#1414)
- [x] remove external typings in DefinitelyTyped after release (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47104)

Please comment if you think there are other tasks we should complete and I can add them to the list. Also comment if you start working on a task

**Comment by davidjgoss** [comment]
Would like to pick up the api-extractor thing if no one objects - won't be short but shouldn't conflict with any of the others.

Also think it might be good to put some guards in with https://www.npmjs.com/package/tsd so we test the typings against typical usages in support code and customer formatters.

**Comment by davidjgoss** [comment]
Update from me - had a go with api-extractor but ran into a corner case issue where re-exporting the `Status` enum from cucumber-messages trips it up. I've gotten some help from the rushstack team and will dig in a little more this week.

Also I can pick up `noImplicitReturns` in next couple of days too.

cc @charlierudolph

**Comment by davidjgoss** [comment]
Draft PR raised for DefinitelyTyped https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47104 - will be mergeable once we release 7.0.0
