### ISSUE TITLE
7.0.0 candidates

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/cucumber-js#1290]
Discussion of what needs to be done before cutting a 7.0.0 release. There is [a milestone](https://github.com/cucumber/cucumber-js/milestone/11) created which concrete issues and PRs can be linked to once they are agreed here.

## TypeScript

- [x] Various fixup tasks (#1269)

## Gherkin & Messages

- [x] Minimal support for `Rule` in out-of-box formatters (#1273) 
- [x] Change messages output to NDJSON instead of binary (#1295)
- [x] Validate message output with CCK, use latest Gherkin, messages etc (#1318)
- [x] Mark the built-in JSON formatter as deprecated (show a warning at runtime?) (#1249)

## Other Breaking Changes?

Do we take the opportunity to make some other breaking changes?

- ~~Make CLI args case consistent (see #1291)~~
- ~~Publish to npm under `@cucumber/cucumber` in line with other packages (see #1411)~~
- ~~Change to how custom formatters are loaded to support external packages (see #1413)~~

**Comment by davidjgoss** [comment]
cc @charlierudolph @aslakhellesoy

**Comment by charlierudolph** [comment]
@aslakhellesoy I looked at the compatibility kit a bit and don't see the binary the readme mentions to actually perform the check.

**Comment by davidjgoss** [comment]
@charlierudolph @aslakhellesoy I got something started for CCK validation here:
https://github.com/cucumber/cucumber-js/pull/1318 (still very WIP, need to sort out making uris, ids and clock predictable).

Most of the differences are because things have moved on since gherkin 9 and messages 8 which we are depending on right now. Do we want to try and bring it up to the latest gherkin and messages before doing a 7.0.0 release? I'm happy to give that a go if it's the right thing to do.

Also I think the CCK has quite a few changes that aren't yet published in the npm package https://github.com/cucumber/cucumber/tree/master/compatibility-kit/javascript.

**Comment by charlierudolph** [comment]
Upgrading gherkin / messages works for me. An long as cck if itself versioned and suppose to work with specific gherkn / messages that should be fin.

**Comment by davidjgoss** [comment]
Still working through these changes.

@mpkorstanje @vincent-psarga are you able to do a release of the JavaScript CCK package with the latest changes?

**Comment by mpkorstanje** [comment]
I wasn't aware those were released. If nobody else gets to it before the end of this week I'll give it a stab.

**Comment by vincent-psarga** [comment]
@davidjgoss what do you exactly mean by a release of the CCK ? For Ruby for example, we don't package the CCK as a gem, we run the feature directly from the mono-repo against the code of `cucumber-ruby` in its branch.

You can see [in the config.yml of cucumber-ruby](https://github.com/cucumber/cucumber-ruby/blob/master/.circleci/config.yml#L138) how each build validates the CCK.
That said, we use a tagged version of the mono-repo, usually the one based on the latest `cucumber-messages` release.

**Comment by davidjgoss** [comment]
@vincent-psarga the JS version of CCK has been packaged up and published to npm - the current published version 1.0.0 is a few months old though https://www.npmjs.com/package/@cucumber/compatibility-kit

If the setup is already there for it, I think using CCK as an npm package would be the cleanest way for us to work with it

(I'm not blocked on this right now as I have copied the content from the monorepo for the time being)

**Comment by davidjgoss** [comment]
Now that the cucumber org has control of the `@cucumber` scope on npm, do we want to rename the package to `@cucumber/cucumber` for the upcoming release?

**Comment by aslakhellesoy** [comment]
Yes, I think we should release as `@cucumber/cucumber` going forward!

**Comment by davidjgoss** [comment]
Per #1428 we have some confusion because of the state of master vs last published version.

Would it be worth doing a “soft” 7.0.0 release and then publicising a closely-following 7.1.0 that includes the reports stuff?

**Comment by davidjgoss** [comment]
@charlierudolph @aslakhellesoy do we feel ready for 7.0.0? We do have https://github.com/cucumber/cucumber-js/pull/1416 open still

**Comment by davidjgoss** [comment]
Closing this now we (I think) have all the big changes in for 7.0.0 that we wanted.

Not sure if we want to do another RC before an official 7.0.0?
